# Generated by Django 5.2.17 on 2026-09-26 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trough',
            name='windowEnd',
            field=models.DateTimeField(blank=True, help_text='批次开始时刻允许的最晚时间；留空表示不限制', null=True, verbose_name='允许窗止'),
        ),
        migrations.AddField(
            model_name='trough',
            name='windowStart',
            field=models.DateTimeField(blank=True, help_text='批次开始时刻允许的最早时间；留空表示不限制', null=True, verbose_name='允许窗起'),
        ),
    ]
